### ISSUE TITLE
Missing tests in source-distribution

### ISSUE THREAD

**Issue by boyska** [ael-code/pyFsdb#10]
Hello!
While writing a debian package for Fsdb, I noticed that the tarball produced with `python setup.py sdist` does not include the `tests/` directory. This is confirmed by the tarball hosted at PyPI.

The convention is shipping tests together with source code, because they are useful for intermediate packagers.

**Comment by boyska** [comment]
will you consider a patch on this?

**Comment by boyska** [comment]
nice! I'll try packaging `1.2.1` for debian testing with unit testing too!

**Comment by ael-code** [comment]
Keep in mind that all the releases from `1.0` to `1.2` are bugged. The `1.2.1` seems to work fine.

**Comment by boyska** [comment]
Of course I'll package the latest one, that is, `1.2.1`. But #16
