### ISSUE TITLE
docs not included in source package

### ISSUE THREAD

**Issue by boyska** [ael-code/pyFsdb#13]
Since docs are not included in the source package as created by sdist, I cannot put them in a `python-fsdb-doc` debian package. similar to #10

**Comment by ael-code** [comment]
fixed in c1a79dc98606c14f230bbf8ebddac35bb3c5cddd

**Comment by boyska** [comment]
ael:

> fixed in c1a79dc98606c14f230bbf8ebddac35bb3c5cddd

False

(I'll assign myself a funny emoji for being python-syntactically valid)

**EDIT**: I can't reopen this issue myself because of dictatorship, but I would if I could. Free @boyska
