### ISSUE TITLE
executable files in tarball

### ISSUE THREAD

**Issue by boyska** [ael-code/pyFsdb#16]
all the files in the 1.2.1 tarball on pypi are executable. This does not match with the status of the git repository.

**Comment by ael-code** [comment]
Fuck `NTFS`. Is this a real problem?

**Comment by boyska** [comment]
ael:

> Fuck `NTFS`

may NTFS be blamed (I don't want to know the horror story about why you
are using NTFS to develop)

> Is this a real problem?

yes it is. Both for obvious security issues (what's going to happen if I
run the README?) and for packaging issues: debian packaging tools
complain about it.
I tried to hack around it, but it is not so easy. So please, please do a
1.2.2 one :)

**Comment by ael-code** [comment]
> I tried to hack around it, but it is not so easy. So please, please do a 1.2.2 one :)

oke

**Comment by ael-code** [comment]
Which permissions would you suggest to use for the tarball?

**Comment by boyska** [comment]
ael:

> Which permissions would you suggest to use for the tarball?

the same that are enforced in the git repository itself. So, only the
directories have +x

**Comment by ael-code** [comment]
Oke I've dropped the NTFS partition and tagged the new version `1.2.2`

Before to release it to the PyPI I would like you to check if the attached tarball is fine.

[Fsdb-1.2.2.tar.gz](https://github.com/ael-code/pyFsdb/files/190439/Fsdb-1.2.2.tar.gz)

**Comment by boyska** [comment]
ael:

> Oke I've dropped the NTFS partition and tagged the new version `1.2.2`
> 
> Before to release it to the PyPI I would like you to check if the attached tarball is fine.

it is

**Comment by ael-code** [comment]
Fixed in the v1.2.2
