### ISSUE TITLE
more pythonic API

### ISSUE THREAD

**Issue by boyska** [ael-code/pyFsdb#4]
I think that it would be very cool if we could have more pythonic statements that do the equivalent of methods like `.add` or `.exists`.

Some example:

``` python
db = Fsdb()
if 'myhashadsadsadasd' in db:
    print "same as exists()!"
    content = db['myhashadsadsadasd']
    db -= 'myhashadsadsadasd' 
    print "just like .remove()"
db += 'newfile'
assert hash('newfille') in db
```

This can easily be done with magic methods like `__iadd__`, `__isub__`, `__contains__`, `__getitem`

**Comment by ael-code** [comment]
I have implemented `__iter__`, `__contains__`, `__len__`.

I do not like the idea that fsdb support `+=` operation:
the `add()` function return the id ( handle ) that you can use to later retrieve the added file. `+=` does not permit to return any value and retrieve the id (handle) is not simple as `hash()`.

For the `__getitem` insetead, which return value do you expect ?

**Comment by boyska** [comment]
> I do not like the idea that fsdb support `+=` operation:
> the `add()` function return the id ( handle ) that you can use to later retrieve the added file. `+=` does not permit to return any value and retrieve the id (handle) is not simple as `hash()`.

Making an operation 'not-so-useful' is not a problem, but I understand
your point

> For the `__getitem` insetead, which return value do you expect ?

I'd like to receive an open buffer. This way it could be more abstract
from the backend. Let's suppose, for example, that someone wants to
implements fsdb over a zipfile. It would be incompatible with returning
a filepath, but returning an open read-only buffer would be perfectly
fine. Or fsdb could actually use some http backend, and thus return an
object created through a urlopen. Oh, and it's also very simple in the
case of normal files.

**Comment by ael-code** [comment]
> I'd like to receive an open buffer. This way it could be more abstract from the backend. Let's suppose, for example, that someone wants to implements fsdb over a zipfile. It would be incompatible with returning a filepath, but returning an open read-only buffer would be perfectly fine. Or fsdb could actually use some http backend, and thus return an object created through a urlopen. Oh, and it's also very simple in the case of normal files.

Fsdb is designed to work on files,  directly using the underlying filesystem. I want to keep it at low level layer. 
It is certainly possible to include fsdb into an higher level module that support files retrieval from multiple backend type ( http, zipfile, etc... ).
For the above reason I implemented the `__getitem__` as to return the file path.

**Comment by boyska** [comment]
The fact that fsdb works with normal files is perfectly correct.
What I don't like much is that who _uses_ fsdb has to deal with file paths. It's a bit like saying that because mysql keep its data in some special file format, even their clients should. I'd like fsdb to abstract more, giving the user exactly what it needs: the _content_.
Another way of putting it is that fsdb is a content-addressable storage. I give an address (that is, the shasum) and want to have the content back. If you return the filepath, you are returning yet another address, which I need to open to have the content. So it actually behaves like an address-mapper.

**Comment by ael-code** [comment]
> The fact that fsdb works with normal files is perfectly correct.
> What I don't like much is that who uses fsdb has to deal with file paths. It's a bit like saying that because mysql keep its data in some special file format, even their clients should. I'd like fsdb to abstract more, giving the user exactly what it needs: the content.
> Another way of putting it is that fsdb is a content-addressable storage. I give an address (that is, the shasum) and want to have the content back. If you return the filepath, you are returning yet another address, which I need to open to have the content. So it actually behaves like an address-mapper.

we use fsdb in libreant mainly for [this line](https://github.com/insomnia-lab/libreant/blob/master/webant/webant.py#L216). Implementing the return of open file descriptor will make things harder.
I also do not like that the flags of `open()` are decided by the library.

**Comment by boyska** [comment]
On Sun, Mar 08, 2015 at 03:56:21AM -0700, ael wrote:

> > The fact that fsdb works with normal files is perfectly correct.
> > What I don't like much is that who uses fsdb has to deal with file paths. It's a bit like saying that because mysql keep its data in some special file format, even their clients should. I'd like fsdb to abstract more, giving the user exactly what it needs: the content.
> 
> we use fsdb in libreant mainly for [this line](https://github.com/insomnia-lab/libreant/blob/master/webant/webant.py#L216). Implementing the return of open file descriptor will make things harder.

this is false. `send_file` accepts open buffers. Just try changing the
first argument with `open(app.fsdb.getFilePath(file['fsdb_id']))`; it works!
So if we make the change, using `send_file(app.fsdb[file['fsdb_id']],
...)` will just work!

> I also do not like that the flags of `open()` are decided by the library.

Well, it should be readonly. And since fsdb should give back the exact
content, 'b' flags should always be added. If we don't do it, we could
give the wrong content. Again, fsdb should give the user the _exact_
content that matches the shasum, not just a filepath: otherwise those
hard decisions are moved to the user, which is the opposite of what
people expects from a library.

**Comment by ael-code** [comment]
On Mar 8, 2015 1:20 PM, "BoySka" notifications@github.com wrote:

> On Sun, Mar 08, 2015 at 03:56:21AM -0700, ael wrote:
> 
> > > The fact that fsdb works with normal files is perfectly correct.
> > > What I don't like much is that who uses fsdb has to deal with file
> > > paths. It's a bit like saying that because mysql keep its data in some
> > > special file format, even their clients should. I'd like fsdb to abstract
> > > more, giving the user exactly what it needs: the content.
> > 
> > we use fsdb in libreant mainly for [this line](https://github.com/insomnia-lab/libreant/blob/master/webant/webant.py#L216).
> > Implementing the return of open file descriptor will make things harder.
> 
> this is false. `send_file` accepts open buffers. Just try changing the
> first argument with `open(app.fsdb.getFilePath(file['fsdb_id']))`; it
> works!
> So if we make the change, using `send_file(app.fsdb[file['fsdb_id']],
> ...)` will just work!

Nice.

> > I also do not like that the flags of `open()` are decided by the
> > library.
> 
> Well, it should be readonly. And since fsdb should give back the exact
> content, 'b' flags should always be added. If we don't do it, we could
> give the wrong content. Again, fsdb should give the user the _exact_
> content that matches the shasum, not just a filepath: otherwise those
> hard decisions are moved to the user, which is the opposite of what
> people expects from a library.

You definitely convinced me. :)

I will change library behaviour as soon as I can.

**Comment by boyska** [comment]
> You definitely convinced me. :)

wow!

> I will change library behaviour as soon as I can.

actually, the `getFilePath` should not be changed behaviour (since the
name is very explicit!); while it **might** be dropped, I think it would
be a pain to handle the transition for users (that is, libreant). So
just leave it is ok for me.

The only function we need to change is `__getitem__`, I believe.

**Comment by ael-code** [comment]
I'll wait for your review to proceed to a new release version.

**Comment by boyska** [comment]
Similarly to what you did for `__getitem__`, I'd also like that `add` is able to also use file-like objects. A simple `hasattr(obj, 'read')` is enough for detecting the correct type. There would be many advantages:
- during unit tests, one could just use StringIO, without needing to create additional temporary files.
- web applications could pass the buffer directly to fsdb, without temporary files

Apart from this, I like the new API. I don't know if you already did, but you should really be explicit about the fact that `getFilePath` does not exist anymore, and its PEP8-compliant equivalent `get_file_path` exists instead. What about keeping ALSO a `getFilePath` that just emits a deprecationwarning and then calls `self.get_file_path`? I think it would make developers that depends on fsdb happier.

**Comment by ael-code** [comment]
your request should be granted by 865bef1842527d4c2ef0f2adeccb6647e0ed0144
