### ISSUE TITLE
check method to ensure that stored files are still valid

### ISSUE THREAD

**Issue by boyska** [ael-code/pyFsdb#5]
Checking that a file `exists()` is useful, but one could wonder whether the file is corrupted. This can be done comparing the filename (that is, its hash) to the actual hash computed on file content.

I propose to add two methods:
- **check_file(digest)** that will check the specific file
- **check_all()** that will check every file in the store.

**Comment by ael-code** [comment]
> check_all() that will check every file in the store.

what should return this function ? bool, list of corrupted files or iterator over corrupted files ?

**Comment by boyska** [comment]
On Fri, Mar 06, 2015 at 02:08:04AM -0800, ael wrote:

> > check_all() that will check every file in the store.
> 
> what should return this function ? bool, list of corrupted files, iterator over corrupted files ?

making it a generator seems perfect. This way, it's up to the caller if
it just want to know whether the store is ok or not (and therefore stop
at first error) or if they want to print everything (and therefore they
want to do a full iteration)

**Comment by ael-code** [comment]
`check()` was implemented in 3c46390e515d8f6c43b2b8eeda1767c9137f26ba
`corrupted()` (check_all) was implemented in c215adedba93cb568a221e9b69fa6678fa7c0811

Do you like them? Are some tests missing?

**Comment by boyska** [comment]
On Fri, Mar 06, 2015 at 04:54:07AM -0800, ael wrote:

> `corrupted()` (check_all) was implemented in c215adedba93cb568a221e9b69fa6678fa7c0811

seeing the code in `corrupted`, I wonder if it works well when
self.fsdbRoot does (or does not) end with a slash. There is that
`rel_dirpath+f` that bugs me, I think that os.path.join would have been
better.

Even the construction of the `rel_dirpath` bugs me a bit. Have you
considered `os.path.relpath` ?

Unit tests seems ok, great!

**Comment by ael-code** [comment]
> There is that `rel_dirpath+f` that bugs me, I think that os.path.join would have been better.

these are not treated as file paths but as strings, so the plus operation is correct.

**Comment by ael-code** [comment]
> Even the construction of the `rel_dirpath` bugs me a bit. Have you considered `os.path.relpath` ?

nice tip. Thanks.

**Comment by boyska** [comment]
On Fri, Mar 06, 2015 at 09:11:15AM -0800, ael wrote:

> > There is that `rel_dirpath+f` that bugs me, I think that os.path.join would have been better.
> 
> these are not treated as file paths but as strings, so the plus operation is correct.

yes, file paths are strings. The point is that I'm worried about the
trailing slash. Concatenating paths is not equivalent to concatenating
strings.

**Comment by ael-code** [comment]
> yes, file paths are strings. The point is that I'm worried about the trailing slash. Concatenating paths is not equivalent to concatenating strings.

I'm concatenating path into a function that removes all the os.sep occurrences. It is not necessary to use os.path.join :)

``` python
rel_dirpath = "as/6sdd/9jk2"
f = "hbc5s8k3dm"
# rel_dirpath+f = as/6sdd/9jk2hbc5s8k3dm
string.replace(rel_dirpath+f, os.sep, "")
# as6sdd9jk2hbc5s8k3dm
```

**Comment by boyska** [comment]
On Fri, Mar 06, 2015 at 09:50:01AM -0800, ael wrote:

> > yes, file paths are strings. The point is that I'm worried about the trailing slash. Concatenating paths is not equivalent to concatenating strings.
> 
> I'm concatenating path into a function that removes all the os.sep occurrences. It is not necessary to use os.path.join :)

gotcha. I hate gotchas, but I'm afraid we'll never agree on a common
code style :) anyway, it's ok.
